#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

/**
 * Parse a single rule markdown file
 * @param {string} filePath - Path to the rule file
 * @returns {object} Parsed rule object
 */
function parseRule(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const fileName = path.basename(filePath, '.md');

  // Extract frontmatter
  const frontmatterMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!frontmatterMatch) {
    throw new Error(`No frontmatter found in ${fileName}`);
  }

  const frontmatter = frontmatterMatch[1];
  const body = content.slice(frontmatterMatch[0].length).trim();

  // Parse frontmatter fields
  const titleMatch = frontmatter.match(/title:\s*(.+)/);
  const impactMatch = frontmatter.match(/impact:\s*(.+)/);
  const impactDescriptionMatch = frontmatter.match(/impactDescription:\s*(.+)/);
  const tagsMatch = frontmatter.match(/tags:\s*(.+)/);

  if (!titleMatch || !impactMatch) {
    throw new Error(`Missing required frontmatter fields in ${fileName}`);
  }

  // Parse tags (comma-separated)
  const tags = tagsMatch ? tagsMatch[1].split(',').map(tag => tag.trim()) : [];

  return {
    fileName,
    title: titleMatch[1].trim(),
    impact: impactMatch[1].trim(),
    impactDescription: impactDescriptionMatch ? impactDescriptionMatch[1].trim() : '',
    tags,
    body,
    fullContent: content
  };
}

/**
 * Validate a parsed rule
 * @param {object} rule - Parsed rule object
 * @returns {object} Validation result
 */
function validateRule(rule) {
  const errors = [];

  // Required fields
  if (!rule.title) errors.push('Missing title');
  if (!rule.impact) errors.push('Missing impact');

  // Impact must be HIGH or MEDIUM
  if (!['HIGH', 'MEDIUM'].includes(rule.impact)) {
    errors.push('Impact must be HIGH or MEDIUM');
  }

  // Check filename prefix matches section
  const sections = {
    'analysis-': 'analysis',
    'staging-': 'staging',
    'convention-': 'convention',
    'timeline-': 'timeline',
    'history-': 'history'
  };

  const matchingSection = Object.keys(sections).find(prefix => rule.fileName.startsWith(prefix));
  if (!matchingSection) {
    errors.push(`Filename must start with valid section prefix: ${Object.keys(sections).join(', ')}`);
  }

  // Check for bad/good examples
  if (!rule.body.includes('**Incorrect:**')) {
    errors.push('Missing **Incorrect:** section');
  }
  if (!rule.body.includes('**Correct:**')) {
    errors.push('Missing **Correct:** section');
  }

  // Check for reference
  if (!rule.body.includes('Reference:')) {
    errors.push('Missing Reference section');
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

/**
 * Get section info from filename
 * @param {string} fileName - Rule filename without extension
 * @returns {object} Section info
 */
function getSectionInfo(fileName) {
  const sections = {
    'analysis-': { id: 'analysis', name: 'Commit Analysis', impact: 'HIGH' },
    'staging-': { id: 'staging', name: 'Staging Strategy', impact: 'HIGH' },
    'convention-': { id: 'convention', name: 'Commit Convention', impact: 'HIGH' },
    'timeline-': { id: 'timeline', name: 'Timeline Control', impact: 'MEDIUM' },
    'history-': { id: 'history', name: 'History Management', impact: 'MEDIUM' }
  };

  for (const [prefix, info] of Object.entries(sections)) {
    if (fileName.startsWith(prefix)) {
      return info;
    }
  }
  return null;
}

/**
 * Compile rules to AGENTS.md format
 * @param {Array} rules - Array of parsed rules
 * @param {object} metadata - Skill metadata
 * @returns {string} Compiled AGENTS.md content
 */
function compileToAgentsMd(rules, metadata) {
  const sections = {};

  // Group rules by section
  rules.forEach(rule => {
    const sectionInfo = getSectionInfo(rule.fileName);
    if (sectionInfo) {
      if (!sections[sectionInfo.id]) {
        sections[sectionInfo.id] = {
          info: sectionInfo,
          rules: []
        };
      }
      sections[sectionInfo.id].rules.push(rule);
    }
  });

  // Generate AGENTS.md content
  let content = `# ${metadata.abstract}

**Version ${metadata.version}**

${metadata.organization}

${metadata.date}

> **Note:**
> This document is generated from rule files in \`skills/chronicle-composer/rules/\`.
> Do not edit this file directly - edit the source rule files instead.

---

## Abstract

${metadata.abstract}

---

## Table of Contents

`;

  // Table of contents
  let tocIndex = 1;
  Object.values(sections).forEach(section => {
    content += `${tocIndex}. [${section.info.name}](#${tocIndex}-${section.info.id}) — **${section.info.impact}**\n`;

    section.rules.forEach((rule, ruleIndex) => {
      content += `   - ${tocIndex}.${ruleIndex + 1} [${rule.title}](#${rule.title.toLowerCase().replace(/\s+/g, '-')})\n`;
    });
    tocIndex++;
  });

  content += `

---

`;

  // Sections
  tocIndex = 1;
  Object.values(sections).forEach(section => {
    content += `## ${tocIndex}. ${section.info.name}

**Impact: ${section.info.impact}**

${section.info.description || 'Guidelines for this section.'}

`;

    section.rules.forEach((rule, ruleIndex) => {
      content += `### ${tocIndex}.${ruleIndex + 1} ${rule.title}

**Impact: ${rule.impact}** - ${rule.impactDescription}

${rule.body}

`;
    });

    content += `---

`;
    tocIndex++;
  });

  return content.trim();
}

module.exports = {
  parseRule,
  validateRule,
  getSectionInfo,
  compileToAgentsMd
};